# Step 1: Import Required Libraries

In this step, we import the required Python libraries.

- **Pandas** is used for data manipulation and analysis.
- **NumPy** is used for numerical operations.

In [22]:
import pandas as pd
import numpy as np

# Step 2: Load the Dataset

The Titanic dataset is loaded into a Pandas DataFrame to perform data preprocessing and analysis.

In [23]:
from google.colab import files

uploaded = files.upload()
import pandas as pd

Saving Titanic-Dataset.csv to Titanic-Dataset (1).csv

# Step 3: Dataset Overview

Before cleaning the dataset, it is important to understand its structure.

This step provides:
- Number of rows and columns
- Data types
- Missing values
- Statistical summary

In [24]:

df = pd.read_csv("Titanic-Dataset.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Observation

The dataset contains missing values in **Age**, **Cabin**, and **Embarked** columns.

These missing values need to be handled before further analysis.

In [26]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [27]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Step 4: Handle Missing Values

Missing values can reduce the quality of analysis.

Actions performed:
- Replaced missing values in **Age** with the median.
- Replaced missing values in **Embarked** with the mode.
- Removed the **Cabin** column because it contains too many missing values.

### Observation

All important missing values have been handled successfully.

The dataset is now cleaner and more reliable for analysis.

In [28]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df.drop("Cabin", axis=1, inplace=True)

# Step 5: Remove Duplicate Records

Duplicate records may produce incorrect analysis results.

This step removes duplicate rows from the dataset.

### Observation

Duplicate records were checked and removed successfully.

This improves data quality.

In [29]:
df.drop_duplicates(inplace=True)

# Step 6: Convert Data Types

Data types were converted to improve efficiency and readability.

In [35]:
df.dtypes

Passenger_ID          int64
Survived              int64
Passenger_Class    category
Name                 object
Gender               object
Age                 float64
SibSp                 int64
Parch                 int64
Ticket               object
Fare                float64
Embarked             object
dtype: object

In [30]:
df["Survived"] = df["Survived"].astype(int)
df["Pclass"] = df["Pclass"].astype("category")

# Step 7: Rename Columns

Column names were renamed to make the dataset easier to understand and maintain.

In [31]:
df.rename(columns={
    "PassengerId":"Passenger_ID",
    "Pclass":"Passenger_Class",
    "Sex":"Gender"
}, inplace=True)

# Step 8: Save the Clean Dataset

After completing all preprocessing steps, the cleaned dataset is saved as a new CSV file.

In [32]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Passenger_ID     891 non-null    int64
 1   Survived         891 non-null    int64
 2   Passenger_Class  891 non-null    category
 3   Name             891 non-null    object
 4   Gender           891 non-null    object
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         891 non-null    object
dtypes: category(1), float64(2), int64(4), object(4)
memory usage: 70.7+ KB

,Passenger_ID,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

# Conclusion

The Titanic dataset was successfully cleaned and preprocessed.

## Summary of Work
- Imported the dataset
- Explored the dataset
- Handled missing values
- Removed duplicate records
- Converted data types
- Renamed column names
- Saved the cleaned dataset

## Final Outcome

The cleaned dataset is now ready for Exploratory Data Analysis (EDA) and Machine Learning.

Thank you.

In [33]:
df.to_csv("Titanic_Cleaned.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!